CREATE PROCEDURE PromoteStudents @STUDIES NVARCHAR(100), @SEMESTER INT
AS
BEGIN
	SET XACT_ABORT ON;
	BEGIN TRAN

	DECLARE @IDSTUDIES INT = (SELECT IDSTUDY FROM STUDIES WHERE NAME = @STUDIES);
	DECLARE @IDENROLLMENT INT = (SELECT IDENROLLMENT FROM STUDIES, ENROLLMENT WHERE STUDIES.IDSTUDY = ENROLLMENT.IDSTUDY AND NAME = @STUDIES AND SEMESTER = @SEMESTER)
	DECLARE @FEN INT = (SELECT IDENROLLMENT FROM STUDIES, ENROLLMENT WHERE STUDIES.IDSTUDY = ENROLLMENT.IDSTUDY AND NAME = @STUDIES AND SEMESTER = @SEMESTER+1)

	IF @IDENROLLMENT IS NULL
		BEGIN
			RAISERROR ( '404 ERROR, ENROLLMENT DOES NOT EXIST',1,1);
		END
		

	IF @FEN IS NULL
		BEGIN

		INSERT INTO ENROLLMENT(IDENROLLMENT, SEMESTER,IDSTUDY,STARTDATE) VALUES((SELECT MAX(IDENROLLMENT)+1 FROM ENROLLMENT),@SEMESTER+1,@IDSTUDIES,GETDATE())
		SET @FEN =  (SELECT IDENROLLMENT FROM STUDIES, ENROLLMENT WHERE STUDIES.IDSTUDY = ENROLLMENT.IDSTUDY AND NAME = @STUDIES AND SEMESTER = @SEMESTER+1)
		END

		UPDATE STUDENT SET IDENROLLMENT = @FEN WHERE IDENROLLMENT = @IDENROLLMENT

	COMMIT
END



EXEC PromoteStudents "AUG",1

DROP PROCEDURE  PromoteStudents;

SELECT * FROM ENROLLMENT
SELECT * FROM STUDIES
SELECT * FROM STUDENT